---
galaxy_info:
  author: Ondrej Faměra 
  description: pacemaker basic cluster role with fence_xvm
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  galaxy_tags:
  - clustering
  - clustering:pacemaker
dependencies:
  - { role: OndrejHome.pcs-modules-2 }
